### ISSUE TITLE
M1,M2,M3

### ISSUE THREAD

**Issue by chj1933** [ahangchen/TFusion#13]
@ahangchen ,你好!陈同学，我想请问一下你关于论文里M1\M2\M3是怎么计算的，具体在代码那里实现的。顺便想请问一下Spatio-temporal pattern in the ‘GRID’ dataset和Spatio-temporal pattern in the ‘Market1501’ dataset.曲线是怎么画出来的，具体代码在那里实现的。冒昧打扰之处，还请见谅！望能解答，谢谢！

**Comment by ahangchen** [comment]
You can have a look at [TrackViz/train/st_filter.py](https://github.com/ahangchen/TrackViz/blob/5a5c8a01d80cf9fa955e2b590a9c65d684554e25/train/st_filter.py#L340). Score fusion is computed in [fusion_st_gallery_ranker](https://github.com/ahangchen/TrackViz/blob/5a5c8a01d80cf9fa955e2b590a9c65d684554e25/train/st_filter.py#L241).  Figure 4 is rendered by Excel on the spatial-temporal data [deltas](https://github.com/ahangchen/TrackViz/blob/5a5c8a01d80cf9fa955e2b590a9c65d684554e25/train/st_estim.py#L89) generated in [st_estim.py](https://github.com/ahangchen/TrackViz/blob/5a5c8a01d80cf9fa955e2b590a9c65d684554e25/train/st_estim.py)

**Comment by ahangchen** [comment]
#10

**Comment by ahangchen** [comment]
#10

**Comment by chj1933** [comment]
@ahangchen  你好！请问我如果源数据集和目标数据集是一样的来源，那我怎么把这个时空信息加进去？请问这个时空信息加进去大概能有多少的提升？

**Comment by ahangchen** [comment]
在TrackViz/ctrl/transfer.py里，将source和target设为一样的就可以做同源fusion，结果可见论文Table3和Table4 TFusion-sup

**Comment by chj1933** [comment]
@ahangchen ，你好！请问哪里可以看到你文章的附录？请问可以加一下你的qq或者微信嘛？我想知道你这个时空信息在已知的条件下，怎么直接使用，可以在哪里调用修改？愿兄弟能给予解答。谢谢！

**Comment by chj1933** [comment]
@ahangchen ，作者，你好！我想问一下你论文中目标数据集的ID信息标签可以通过视觉分类器C判断，但目标数据集的摄像头信息和帧号信息你是怎么构造的？还是说这些信息是已知的嘛？

**Comment by ahangchen** [comment]
CVPR官网上可以看到附录：

http://openaccess.thecvf.com/content_cvpr_2018/Supplemental/0779-supp.pdf

摄像头信息和帧号是数据集中已知的，可以看experiment部分，这种数据在现实场景中比行人图像标注要容易获取很多，可以直接由摄像头产生。

**Comment by chj1933** [comment]
@ahangchen 同学你好：
       
               想问一下你统计grid数据集的时空分布是怎么统计的？因为grid数据集的train(250)/gallery(900)/query(125)图片都很少，所以问一下你统计时空分布是只统计train里面的图片，还是所有的图片，你取的帧差还是100？因为你论文里在grid数据集上说时空分布更明显效果跟好。冒昧来信，恳请解惑。谢谢！


                                                              祝：身体健康！学业有成！

**Comment by ahangchen** [comment]
只统计 train 250的时空分布

**Comment by chj1933** [comment]
@ahangchen 请问你统计的帧差范围多大margin?

**Comment by ahangchen** [comment]
100，你可以从[代码](https://github.com/ahangchen/TrackViz/blob/5a5c8a01d80cf9fa955e2b590a9c65d684554e25/train/st_filter.py#L233)中得到这些信息的
