### ISSUE TITLE
market-grid视觉迁移

### ISSUE THREAD

**Issue by Springmm** [ahangchen/TFusion#15]
作者您好，我在复现source为market1501数据集，target为grid数据集的视觉迁移的代码，发现一个bug。在rank-reid/rank-reid.py中的第29行是不是target_gallery_path = target_dataset_path + '/gallery' 结果才正确的。希望作者能够核对下，谢谢。

**Comment by ahangchen** [comment]
由于market数据集默认命名为test，所以我们沿用了这个风格，将全部gallery命名为了test，另外中文讨论请到这里 #10
