### ISSUE TITLE
When use TrackViz transfer.py get IndexError

### ISSUE THREAD

**Issue by MSC19950601** [ahangchen/TFusion#16]
Traceback (most recent call last):
  File "ctrl/transfer.py", line 133, in <module>
    dataset_fusion_transfer()
  File "ctrl/transfer.py", line 126, in dataset_fusion_transfer
    fusion_transfer(source, 'grid-cv%d' % i)
  File "ctrl/transfer.py", line 99, in fusion_transfer
    fusion_test_rank_pids_path, fusion_test_rank_scores_path = st_fusion(source, target)
  File "ctrl/transfer.py", line 48, in st_fusion
    init_strict_img_st_fusion()
  File "/home/msc/Github/person_reid/TFusion/TrackViz/ctrl/img_st_fusion.py", line 50, in init_strict_img_st_fusion
    get_predict_delta_tracks(fusion_param)
  File "./train/st_estim.py", line 91, in get_predict_delta_tracks
    if real_tracks[i][3] == real_tracks[predict_pid][3] and real_tracks[i][1] != real_tracks[predict_pid][1]:
**IndexError: list index out of range**

**Comment by ahangchen** [comment]
This error is usually caused by unmatched predict_pid & i & real_tracks range .  More informations of the variables are needed.

- which target dataset is used?
- which variable is the error index? i or predict_pid? what's the shape of real_tracks?
- have you correctly prepared track info file(corresponding to answer_path) for your target dataset? this file is [parsed](https://github.com/ahangchen/TFusion/blob/master/TrackViz/train/st_estim.py#L36) before computing spatial temporal pattern. Parsing rules are different for different dataset.


Furthermore, your code seems to be different from the published version according to different line number (93 vs 78)of the crash line.  More modification details should be provided.

**Comment by MSC19950601** [comment]
Thank you for quick reply.
The target dataset is grid_cross0. 
i and predict_pid are 0, 344.
real_tracks shape is (250, 4)
I know id index out of list. 
I thought it's the dataset problem.
**Could give me your experiment dataset from baiduyunpan or others?**
For the track info file, I didn't prepare it, **Could you give a sample?**
For the different line problem, I write the 'print()' codes, no damage to the publish one.

**Comment by ahangchen** [comment]
predict_pid is created from renew_pid, meaning the file in such path: TrackViz/data/market_grid_cross0-train/renew_pid.log. This file is generated by the [visual classifier](https://github.com/ahangchen/TFusion/blob/master/rank-reid/rank_reid.py#L22), you need to make the visual classifier work on the right target dataset's training set. How many images are there in your grid_cross0/train directory?

**Comment by MSC19950601** [comment]
1275 images in grid_cross0/train directory, it should be same size and image id as your data file?

**Comment by ahangchen** [comment]
It's different. GRID claims a 10-time-2-fold cross-validation, so we divide the dataset as they suggest. Details of train-probe-gallery division is listed here: https://github.com/ahangchen/TFusion/tree/master/TrackViz/data/grid

**Comment by MSC19950601** [comment]
Under your guidance, the issue before has been solved. 
However, bring out a new issue.
Output is that:
**/home/msc/Github/person_reid/TFusion/TrackViz/data/market_grid-cv0-test/renew_pid.log
[0.0, 0.008, 0.016, 0.016, 0.032]
left image ready
predict images ready
deltas collected
deltas sorted
deltas saved
left image ready
predict images ready
deltas collected
deltas sorted
deltas saved
left image ready
predict images ready
deltas collected
deltas sorted
deltas saved
fusion on training dataset
img score ready
above person score ready
0.02941583853920899
fusion on test dataset
copy train track distribute pickle done
probe and gallery tracks ready
read vision scores and pids ready
load track deltas ready
load rand deltas ready
load diff deltas ready
Traceback (most recent call last):
  File "ctrl/transfer.py", line 133, in <module>
    dataset_fusion_transfer()
  File "ctrl/transfer.py", line 126, in dataset_fusion_transfer
    fusion_transfer(source, 'grid-cv%d' % i)
  File "ctrl/transfer.py", line 99, in fusion_transfer
    fusion_test_rank_pids_path, fusion_test_rank_scores_path = st_fusion(source, target)
  File "ctrl/transfer.py", line 48, in st_fusion
    init_strict_img_st_fusion()
  File "/home/msc/Github/person_reid/TFusion/TrackViz/ctrl/img_st_fusion.py", line 74, in init_strict_img_st_fusion
    iter_strict_img_st_fusion(on_test=True)
  File "/home/msc/Github/person_reid/TFusion/TrackViz/ctrl/img_st_fusion.py", line 115, in iter_strict_img_st_fusion
    test_fusion(fusion_param)
  File "/home/msc/Github/person_reid/TFusion/TrackViz/ctrl/img_st_fusion.py", line 29, in test_fusion
    fusion_st_gallery_ranker(fusion_param)
  File "./train/st_filter.py", line 303, in fusion_st_gallery_ranker
    rand_track_scores = gallery_track_scores(query_tracks, gallery_tracks, rand_delta_s, fusion_param)
  File "./train/st_filter.py", line 224, in gallery_track_scores
    time2 = gallery_tracks[pid4probe][2]
IndexError: list index out of range**

**Comment by ahangchen** [comment]
I think this is caused by similar issues on gallery images. Please make sure that your image number in cross0/gallery is the same as the division in my last comment.

**Comment by MSC19950601** [comment]
However, all cross folders are same as the description files in your repo.
But, every line in the gallery.txt file is same which txt file? grid-cv%d-gallery.txt or grid-cv%d-test.txt?

**Comment by ahangchen** [comment]
All cross folders are different.You would know GRID Gallery images share 775 unlabeled images and 125 labeled images in gallery for each cross if you have read GRID dataset's instruction. I think you only glance at the gallery file and only notice the `shared 775 unlabeled images` while ignore` 125 different labeled images` in each cross.
I'm sorry that grid-cv%d-gallery.txt is exactly the same with grid-cv%d-test.txt, but we only use grid-cv%d-gallery.txt so it doesn't matter.
