### ISSUE TITLE
No such file or directory: 'data/market_grid-cv0-train/renew_pid.log'

### ISSUE THREAD

**Issue by mmchen88** [ahangchen/TFusion#18]
After running rank-reid/pair_train.py, I got many XXXX_pair_train.h5 models.
Then I run TrackViz/crtl/transfer.py, I got:
FileNotFoundError: [Errno 2] No such file or directory: 'data/market_grid-cv0-train/renew_pid.log'.
So, how can I get this log flie?

**Comment by ahangchen** [comment]
This file records image ids matrix sorted by img pairs' similarities. It's generated by [vision_rank and dataset_eval](https://github.com/ahangchen/TFusion/blob/master/TrackViz/ctrl/transfer.py#L94). Please check if there are any errors when you run ctrl/transfer.py at this point.

**Comment by mmchen88** [comment]
got it! I didn't change the python path in vision_rank
