### ISSUE TITLE
FAQ: about Dataset

### ISSUE THREAD

**Issue by ahangchen** [ahangchen/TFusion#2]
Q: 在grid交叉验证分组具体是如何分组的呢，是需要自己人为的分组么还是需要其他什么操作？

A: 参考[GRID官网](http://personal.ie.cuhk.edu.hk/~ccloy/downloads_qmul_underground_reid.html)说明进行划分，我划分好的结果在[这个目录](https://github.com/ahangchen/TrackViz/tree/5a5c8a01d80cf9fa955e2b590a9c65d684554e25/data/grid)

Q: 请问一下论文发表以后你们有做跟DukeMTMC-ReID数据集相关的实验吗?
A: 恩，正在做，提升程度跟market1501差不多

**Comment by rintiunse** [comment]
cuhk01的命名方式好像更改了，请问你读取类别是根据“_"来判断的嘛？

**Comment by ahangchen** [comment]
是的
