### ISSUE TITLE
transfer.py 运行有错，不太懂

### ISSUE THREAD

**Issue by geloveyou** [ahangchen/TFusion#22]
作者你好  ，在Python transfer.py 选用的是source 是Grid  target是market 只在了train融合了，test融合出错了，
![image](https://user-images.githubusercontent.com/45594906/58310083-5fadba00-7e38-11e9-9a33-1fd544acde3c.png)
这个是什么原因啊？还有这张图片是运行Transfer 一次生成的嘛？
![image](https://user-images.githubusercontent.com/45594906/58310229-b1eedb00-7e38-11e9-99a2-53ffb36c9825.png)
我只生成了关于train 的融合 ，其他部分的融合没有生成

**Comment by ahangchen** [comment]
#10
