### ISSUE TITLE
test生成文件不全

### ISSUE THREAD

**Issue by geloveyou** [ahangchen/TFusion#23]
作者你好
![image](https://user-images.githubusercontent.com/45594906/58545471-e5b17280-8235-11e9-9e41-46b55cb15feb.png)
![image](https://user-images.githubusercontent.com/45594906/58545495-f4982500-8235-11e9-8a49-5ef1f492f1c9.png)
为什么我这两个生成不了融合后的结果？
还有的是
![image](https://user-images.githubusercontent.com/45594906/58545567-1beef200-8236-11e9-904d-d5399e7792df.png)这个如何修改对融合后的进行评估？

**Comment by ahangchen** [comment]
#10
