### ISSUE TITLE
论文附录中的证明部分

### ISSUE THREAD

**Issue by ghost** [ahangchen/TFusion#5]
看了您的文章，有一些地方不太明白。。
1.公式26是怎样得到的，并且为什么将公示23和24划等号，一个反应图像模型的概率，一个反应混合模型的概率，这两个模型是一个相互促进的关系，为什么可以划等号。
2.后续的求梯度的原因是什么

**Comment by ahangchen** [comment]
The max number of Equation in the appendix is 18. So I can't figure out which Eq you refer to is. BTW, I think we didn't mention about gradient as well.
