### ISSUE TITLE
关于.log 文件生成的问题

### ISSUE THREAD

**Issue by 18177384057** [ahangchen/TFusion#6]
您好，请问这些.log文件是运行哪些程序生成的呢？![cutter_2018-07-18 11_43_07 553](https://user-images.githubusercontent.com/41353935/42858171-c77f9cbe-8a7f-11e8-8e22-8f89238a64df.png)
另外，要运行的文件不少，能不能麻烦您按下面的图上的序号排一下运行的先后顺序？
![tfusion](https://user-images.githubusercontent.com/41353935/42858303-7d42bff4-8a80-11e8-953e-dc8a8b541cdc.png)
十分感谢！！！

**Comment by ahangchen** [comment]
Log(actually they are experiment results) are generated by rank-reid/rank-reid.py calledy by TrackViz/ctrl/transfer.py. Actually, you only need to modify the pathes, pretrain models using rank-reid/pair_train.py, then run ctrl transfer.py. Details are instructed in TFusion README.

**Comment by 18177384057** [comment]
模型训练好了，路径也改了，运行transfer.py，只有cuhk_market-train,,cuhk_market-test这些文件夹，但里面是空的，没有保存的.log文件。

**Comment by 18177384057** [comment]
你好，rank-reid/pretrain/路径下的pair_transfer.py 怎么没有呢？可以上传上去吗？
![cutter_2018-07-19 04_22_57 184](https://user-images.githubusercontent.com/41353935/42930728-644e42b6-8b70-11e8-9bda-f580c133beec.png)

**Comment by ahangchen** [comment]
- renew_pid.log and renew_ac.log are produced in [rank-reid project](https://github.com/ahangchen/rank-reid/blob/master/rank_reid.py#L27) when called by [TrackViz/ctrl/transfer.py](https://github.com/ahangchen/TrackViz/blob/release/ctrl/transfer.py#L127). Read the code in the hyper link and you will understand the schedule.

- pair_transfer.py isn't used in the release code, so we remove it.

**Comment by 18177384057** [comment]
十分感谢！！！

**Comment by 18177384057** [comment]
不好意思，再请教一下，cross_filter_pid.log是哪个文件生成的？

**Comment by ahangchen** [comment]
You can search cross_filter_pid.log in the project to understand the generation procedure.

**Comment by 18177384057** [comment]
![image](https://user-images.githubusercontent.com/41353935/43054985-ba27cbaa-8e66-11e8-83e7-faed80df7078.png)
查看了所有的程序，只有读，没有写入。不知道怎么解决？

**Comment by Huangdai** [comment]
我也遇到了这个问题，生成不了log文件。

**Comment by houzhenzhen** [comment]
@ahangchen  
你好，cross_filter_pid.log 这个文件是什么意思？ 怎么生成的，找不到 谢谢

**Comment by ahangchen** [comment]
@Huangdai Look at [these lines](https://github.com/ahangchen/rank-reid/blob/master/rank_reid.py#L27) and make sure they are the same with the TrackViz @ 5a5c8a0 

@houzhenzhen you can search in TrackViz, it's defined in profile/fusion_param.py

Attention: make sure you are using the repos with commit id specified in TFusion. You should use TrackViz@5a5c8a0 and rank-reid@b228897 because the master branches of TrackViz and rank-reid are under developing, so you will meet some errors if you use other version repos.

**Comment by YuehuaZhu** [comment]
作者你好，我也在仿真你的代码，可是按你的操作实践起来很困难，比如log文件缺失，但你也并没有在readme.md中写明如何生成log文件，真的很不友好~

**Comment by ahangchen** [comment]
@YuehuaZhu 如果你按照readme的流程操作是不会有文件缺失的问题的，文档不能包含所有的细节，在这个issue里我已经补充过这些文件的来源了。
