### ISSUE TITLE
关于 No such layer: avg_pool

### ISSUE THREAD

**Issue by 1067219243** [ahangchen/TFusion#7]
作者您好，当我运行pair_train.py 时，提示我 No such layer: avg_pool，请问我该怎么解决？

root@9dde0b706344:/home/hyl/TFusion/rank-reid/pretrain# python pair_train.py
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File "pair_train.py", line 228, in <module>
    pair_pretrain_on_dataset(source)
  File "pair_train.py", line 219, in pair_pretrain_on_dataset
    batch_size=batch_size, num_classes=class_count
  File "pair_train.py", line 155, in pair_tune
    model = pair_model(source_model_path, num_classes)
  File "pair_train.py", line 123, in pair_model
    base_model = Model(inputs=softmax_model.input, outputs=[softmax_model.get_layer('avg_pool').output], name='resnet50')
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/network.py", line 365, in get_layer
    raise ValueError('No such layer: ' + name)
ValueError: No such layer: avg_pool

**Comment by ahangchen** [comment]
softmax_model is a simple resnet50 model. Maybe ResNet in your keras version hasn't the avg_pool layer? This repo is built on keras 2.1.5. You can print softmax_model.layers to see what layers softmax model containing.
