### ISSUE TITLE
关于“answer_path”

### ISSUE THREAD

**Issue by 1067219243** [ahangchen/TFusion#9]
作者您好，请问这里https://github.com/ahangchen/TrackViz/blob/5a5c8a01d80cf9fa955e2b590a9c65d684554e25/profile/fusion_param.py#L16
answer_path,  test_tracks.txt是什么？

**Comment by ahangchen** [comment]
You can see [these Lines](https://github.com/ahangchen/TrackViz/blob/5a5c8a01d80cf9fa955e2b590a9c65d684554e25/profile/fusion_param.py#L35), test_tracks.txt is a initialized string, which will be reset to 'train.list' or 'probe.list' by get_fusion_param(). These files have been listed in TrackViz/data

**Comment by 1067219243** [comment]
好的，谢谢。
